In [2]:
import numpy as np

In [3]:
list1 = [1, 2, 3]
list2 = [[10], [20], [30]]
vector1 = np.array(list1)
vector2 = np.array(list2)

In [4]:
print("Horizontal Vector")
vector1

Horizontal Vector


array([1, 2, 3])

In [5]:
print("----------------")

----------------


In [6]:
print("Vertical Vector")
vector2

Vertical Vector


array([[10],
       [20],
       [30]])

In [7]:
vector = np.arange(1, 10)

print("Vector using arange:")
vector

Vector using arange:


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
vector = np.linspace(0, 10, 5)

print("Vector using linspace:")
vector

Vector using linspace:


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
vector_zeros = np.zeros(5)

print("Vector using zeros:")
vector_zeros

Vector using zeros:


array([0., 0., 0., 0., 0.])

In [13]:
vector_ones = np.ones((3, 4))

print("Vector using ones:")
vector_ones

Vector using ones:


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Basic Arithmetic Operations on Vectors

In [14]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

vector1 = np.array(list1)

print("First Vector:" + str(vector1))

vector2 = np.array(list2)

print("Second Vector:" + str(vector2))

addition = vector1 + vector2

print("Addition of Vectors:" + str(addition))

subtraction = vector1 - vector2

print("Subtraction of Vectors:" + str(subtraction))

multiplication = vector1 * vector2

print("Multiplication of Vectors:" + str(multiplication))

division = vector1 / vector2

print("Division of Vectors:" + str(division))

First Vector:[1 2 3]
Second Vector:[4 5 6]
Addition of Vectors:[5 7 9]
Subtraction of Vectors:[-3 -3 -3]
Multiplication of Vectors:[ 4 10 18]
Division of Vectors:[0.25 0.4  0.5 ]


In [15]:
import numpy as np

list1 = [5, 6, 9]
list2 = [1, 2, 3]

vector1 = np.array(list1)
print("First Vector  : " + str(vector1))

vector2 = np.array(list2)
print("Second Vector : " + str(vector2))

dot_product = np.dot(vector1, vector2)
print("Dot Product of Vectors: " + str(dot_product))

First Vector  : [5 6 9]
Second Vector : [1 2 3]
Dot Product of Vectors: 44


In [16]:
import numpy as np

list1 = [1, 2, 3]

vector = np.array(list1)
print("Vector  : " + str(vector))

scalar = 3
print("Scalar : " + str(scalar))

scalar_multiplication = vector * scalar
print("Scalar Multiplication : " + str(scalar_multiplication))

Vector  : [1 2 3]
Scalar : 3
Scalar Multiplication : [3 6 9]
